### ISSUE TITLE
AREkit-0.24.0 What's new

### ISSUE THREAD

**Issue by nicolay-r** [nicolay-r/AREkit#488]
- [x] :fire: #296 

### Improvements
- [x] #527
- [x] automate `NoFolding` support, easy API usage :fire:  #466
- [x]  :wrench:  #417 
- [x] :wrench: #489 
- [x] :wrench: #502 because of #501 were fixed
- [x] :wrench: #510 
- [x] #503 
- [x] #507
- [x] remove everything related to applications and related framework if everything will be OK with the paper (0.23.1 as well)
- [x] #520 
- [x] :wrench: #526  

### Generalization
- [x] Long delayed issue: #284
- [x] API: doc renaming #457 
- [x] #522 

### Changes and Simplifications
- [x] :x: #517 
 - [x] :x:  Drop support of reading grouped Opinions (#491 and #492 related) [the related unit-test was optional and has been removed as well)
 - [x] :x:  #483 
 - [x] :x:  #376 

### Minor
- [x] #521 
- [x] #505
- [x] #514
- [x] #534 
- [x] Make to string for `doc_now` parameter:
![image](https://github.com/nicolay-r/AREkit/assets/14871187/dc619e81-1b68-4f9b-8cc6-d3fb64d48904)

**Comment by nicolay-r** [comment]
:partying_face:
