### ISSUE TITLE
What's new in 0.25.0

### ISSUE THREAD

**Issue by nicolay-r** [nicolay-r/AREkit#536]
# Support `Batching` for effecting imputing LLM into text processing pipelines
Previosly, the whole text processing pipeline was relying on the `sentence` / text part. 
Now we overcome that liimitation and therefore we can consider multiple sentences, formed in list i.e. batch.
This step is so important for LLM, LM, neural networks, for which batching accelerates the performance.
As the result, overall pipeline launching is expected to perform faster.
 
- [x] nicolay-r/AREkit#539 :fire: 
- [x] nicolay-r/AREkit#535 
- [x] nicolay-r/AREkit#540
- [x] #541 

Sources collections are no longer going to be a part of AREkit :sparkles: 
Tha allow us to lightweight :feather: the overall framework and so that purely focus on data processing techniques
- [x] nicolay-r/AREkit#537
- [x] Remove `requests` library dependency  :feather: 
- [x] Move all the tutorials :books:  to the `AREkit-ss` project. :feather: 

# Flexibility and Performance Enhancements
- [x] nicolay-r/AREkit#539 :fire: 
- [x] nicolay-r/AREkit#535 
- [x] nicolay-r/AREkit#537
- [x] nicolay-r/arekit-ss#80 (Issue has been moved to `arekit-ss` project)
    - [x] ~~nicolay-r/AREkit#511~~
- [x] nicolay-r/AREkit#538
- [x] #542 :wrench:  
# Fixed bugs
- [x] :wrench: `RowCacheStorageProvider` fixed bug with mismatching size of type list and columns list in case of other `force` collected columns   (https://github.com/nicolay-r/AREkit/commit/ad4312c40c142c37278967e04870e4086591113a)
# Minor Updates
- [x] :x: Removed `OpinionsIO` (https://github.com/nicolay-r/AREkit/commit/76b4c1fef954f03724932d397c9a147c23dcf20c)
- [x] :x: Removed suffix `-0` in filenames for samples.  (https://github.com/nicolay-r/AREkit/commit/76b4c1fef954f03724932d397c9a147c23dcf20c)
- [x] :x: #543 
- [x] :x: #544
- [x] :x: #547

**Comment by nicolay-r** [comment]
Published :partying_face:
